version: "3"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.app
      args:
        WORK: "/usr/src/dodosoft"
    volumes:
      # ソースコード一式マウント
      - "..:/usr/src/dodosoft:delegated"
      # 起動スピード向上のためgem関連を保存しておく
      - "./data/app/bundle/gems:/usr/local/bundle/gems:delegated"
      - "./data/app/bundle/cache:/usr/local/bundle/cache:delegated"
      - "./data/app/bundle/extensions:/usr/local/bundle/extensions:delegated"
      - "./data/app/bundle/specifications:/usr/local/bundle/specifications:delegated"
      - "./data/app/bundle/.bundle:/root/.bundle:delegated"
    environment:
      DSOFT_DATABASE_DEV_USER: postgres
      DSOFT_DATABASE_DEV_HOST: postgres
      BASIC_AUTH_USERNAME: admin
      BASIC_AUTH_PASSWORD: password
    ports:
      - "3000:3000"
  postgres:
    build:
      context: .
      dockerfile: Dockerfile.postgres
    volumes:
      # DBのデータ永続化
      - "./data/postgres:/var/lib/postgresql/data:delegated"
      # 初回起動時dsoftデータベース作成
      - "./init-user-db.sh:/docker-entrypoint-initdb.d/init-user-db.sh:delegated"